version: 1.0.{build}
image: Windows Server 2019

environment:
  DOCKER_USER: bchsitecore
  DOCKER_PASS:
    secure: rBZnM8JQZGVmMu5zdYP5Qw==
  DOCKER_REPO: sitecoreinstallframework

install:
  - ps: Write-Host Server version $(Get-ItemProperty 'HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion').BuildLabEx
  - cmd: docker version
build_script:
  - ps: |
      $env:DOCKER_PASS | docker login --username $env:DOCKER_USER --password-stdin
      .\Build.ps1 -Repository "${env:DOCKER_USER}/${env:DOCKER_REPO}"
after_build:
  - docker images

notifications:
  - provider: Slack
    incoming_webhook:
      secure: 6xD2ujsiPvtwxG7+lDge0d8+J7sJQjXcNZbUe2aiz7jOl1mSPDUPsISWu7mOYV9KB81PFyawE+csJ0H8j6sixUbc3j9CLK9bU9++I9J5S0E=